### ISSUE TITLE
Maintainer request

### ISSUE THREAD

**Issue by rammba** [reactjs/sr.react.dev#68]
### Summary

Hello guys, I found out this repository recently and I'm willing to help a little bit.

### Details

I'm not a react developer and I have almost zero knowledge about it currently. I have working experience mostly in Angular.
On the other hand, I have some translation experience, mostly with Steam games. Also, I had a contact with @lxmarinkovic recently on Semver (https://github.com/semver/semver.org/pull/445).

**Comment by lxmarinkovic** [comment]
Sure, your help would be appreciated! I'll add you during the day 😃🚀

**Comment by lxmarinkovic** [comment]
you should find invite in your inbox :D

**Comment by lxmarinkovic** [comment]
you should find invite in your inbox :D

**Comment by rammba** [comment]
Thanks for the chance!
