### ISSUE TITLE
List of frequent used words

### ISSUE THREAD

**Issue by rammba** [reactjs/sr.react.dev#73]
Since there are four of us here, and potentially more people in the future, I think we need a list of the most used words in the text.

It can happen that multiple people come across the same word, so we need some kind of a "rule" how to translate it. Even if one person translates whole text, it can forget which word was used long ago.

We can create readme file on the repo, or something similar just to keep track.

For example:
feature -> funkcionalnost
UI -> korisnički interfejs
open source -> otvoreni kod
framework -> framework
deploy -> deploy
endpoint -> pristupna tačka

None of these are carved in the stone, but I think we should make consensus which words to use. We should also think about whether to use english word (eg. deploy) or serbian word (eg. pristupna tačka) for some terms.

**Comment by lxmarinkovic** [comment]
@rammba, you can check out our translations so far. We decided not to translate industry-standard terms that are usually untranslatable or create unnecessary confusion. For example, open source would come as open source, then hyphenated with the suffix a, ov, etc.
I think this would be a rule of thumb; therefore, no further guidelines are necessary :D

**Comment by rammba** [comment]
I'm checking current translations just to grasp terms that you guys already "defined".
The idea of this issue was mostly to define which of those widely known terms should/shouldn't be translated.

**Comment by lxmarinkovic** [comment]
Good 👍 
You will notice that industry, especially React terms, are enforced to stay in English as a defacto standard. Insisting on literally translating would confuse both the maintainer and the reader. Those words are widely accepted in the React community, and there are no reasons why we shouldn't use them. Having a rule of thumb is much more effective than an exhaustive list of definitions and guidelines, which, trust me, would be just counterproductive and would introduce a layer of confusion to the reader :D

**Comment by rammba** [comment]
Since I don't have much experience in translating technical stuff like this, I appreciate your suggestions. I will try not to translate standardized words, but to keep the original for simplicity.
