### ISSUE TITLE
Domain sr.react.dev

### ISSUE THREAD

**Issue by rammba** [reactjs/sr.react.dev#78]
Hello @gaearon @lxmarinkovic, I've noticed that domain of the Serbian deployed version is [sr-react-dev.vercel.app](https://sr-react-dev.vercel.app/), not [sr.react.dev](https://sr.react.dev/).

Main version of the application is referencing to the `https://${code}.react.dev/` which is not valid in our case. New users can potentially click on the Serbian link willing to read docs on their mother tongue, but the error will appear.
![image](https://github.com/user-attachments/assets/3568d2be-c0b4-4651-a59f-aa1cda174e1b)

I've noticed that Vercel started appearing in the domain for all the languages after Vietnamese.
Can you please investigate and potentially fix this?

**Comment by lxmarinkovic** [comment]
> Hello @gaearon @lxmarinkovic, I've noticed that domain of the Serbian deployed version is [sr-react-dev.vercel.app](https://sr-react-dev.vercel.app/), not [sr.react.dev](https://sr.react.dev/).
> 
> 
> 
> Main version of the application is referencing to the `https://${code}.react.dev/` which is not valid in our case. New users can potentially click on the Serbian link willing to read docs on their mother tongue, but the error will appear.
> 
> ![image](https://github.com/user-attachments/assets/3568d2be-c0b4-4651-a59f-aa1cda174e1b)
> 
> 
> 
> I've noticed that Vercel started appearing in the domain for all the languages after Vietnamese.
> 
> Can you please investigate and potentially fix this?
> 
> 

@rammba I wrote explanation on Discord, so will close this issue

**Comment by lxmarinkovic** [comment]
@rammba I wrote explanation on Discord, so will close this issue
